version: '3.9'
services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - 5436:5432

  redis:
    image: redis
    restart: always
    volumes:
      - ./db/redis:/data
    ports:
      - 6379:6379

volumes:
  db:
    driver: local